[2025-07-31T13:27:16.422+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T13:27:16.483+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_monitoring_dag.check_drift_and_trigger scheduled__2025-07-31T12:00:00+00:00 [queued]>
[2025-07-31T13:27:16.496+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_monitoring_dag.check_drift_and_trigger scheduled__2025-07-31T12:00:00+00:00 [queued]>
[2025-07-31T13:27:16.517+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-31T13:27:16.539+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): check_drift_and_trigger> on 2025-07-31 12:00:00+00:00
[2025-07-31T13:27:16.573+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'drift_monitoring_dag', 'check_drift_and_trigger', 'scheduled__2025-07-31T12:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/drift_monitoring.py', '--cfg-path', '/tmp/tmpl_6ab8sd']
[2025-07-31T13:27:16.578+0000] {standard_task_runner.py:91} INFO - Job 204: Subtask check_drift_and_trigger
[2025-07-31T13:27:16.581+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4483) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-31T13:27:16.583+0000] {standard_task_runner.py:63} INFO - Started process 4537 to run task
[2025-07-31T13:27:16.611+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-31T13:27:16.689+0000] {task_command.py:426} INFO - Running <TaskInstance: drift_monitoring_dag.check_drift_and_trigger scheduled__2025-07-31T12:00:00+00:00 [running]> on host 44c57df83f33
[2025-07-31T13:27:16.869+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_monitoring_dag' AIRFLOW_CTX_TASK_ID='check_drift_and_trigger' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-31T12:00:00+00:00'
[2025-07-31T13:27:16.872+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T13:27:16.905+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T13:27:16.907+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/drift_monitoring.py", line 106, in check_drift_and_trigger
    pred_df = load_parquet(BUCKET_NAME, pred_key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/drift_monitoring.py", line 56, in load_parquet
    obj = s3_client.get_object(Bucket=bucket, Key=key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 964, in _make_api_call
    api_params = self._emit_api_params(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1083, in _emit_api_params
    self.meta.events.emit(
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/handlers.py", line 295, in validate_bucket_name
    if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'dict'
[2025-07-31T13:27:16.994+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=drift_monitoring_dag, task_id=check_drift_and_trigger, execution_date=20250731T120000, start_date=20250731T132716, end_date=20250731T132716
[2025-07-31T13:27:17.028+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 204 for task check_drift_and_trigger (expected string or bytes-like object, got 'dict'; 4537)
[2025-07-31T13:27:17.093+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-31T13:27:17.130+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-31T13:27:17.134+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
